### ISSUE TITLE
segfault when opening non-existing /dev/snd/seq

### ISSUE THREAD

**Issue by rekado** [powertab/powertabeditor#180]
Powertabeditor segfaults when I try to play back a tab and when I open the preferences.  On the terminal I see that it fails to open /dev/snd/seq which does not (yet) exist on my system as I haven't loaded the appropriate kernel module.

**Comment by cameronwhite** [comment]
Would you be able to provide a stack trace? I'm on a Windows machine right now so it probably won't be easy for me to reproduce it myself.

**Comment by rekado** [comment]
> Would you be able to provide a stack trace? I'm on a Windows machine
> right now so it probably won't be easy for me to reproduce it myself.

This is the somewhat unhelpful stack trace that's shown in the "Error"
window (is there an easy way to build with debug symbols?):

~~~~~~~~~~~~~~~~~
Segmentation fault
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [???]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [???]
/gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6 [???]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [MidiOutputDevice::MidiOutputDevice]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [PreferencesDialog::PreferencesDialog]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [PowerTabEditor::editPreferences]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [???]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QMetaObject::activate]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QAction::triggered]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QAction::activate]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [???]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [???]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QMenu::mouseReleaseEvent]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QWidget::event]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QMenu::event]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QApplicationPrivate::notify_helper]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QApplication::notify]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QCoreApplication::notifyInternal]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QApplicationPrivate::sendMouseEvent]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [???]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [???]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QApplicationPrivate::notify_helper]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Widgets.so.5 [QApplication::notify]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QCoreApplication::notifyInternal]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Gui.so.5 [QGuiApplicationPrivate::processMouseEvent]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Gui.so.5 [QGuiApplicationPrivate::processWindowSystemEvent]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Gui.so.5 [QWindowSystemInterface::sendWindowSystemEvents]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/plugins/platforms/libqxcb.so [???]
/gnu/store/j02321iwdqyrpdrd53ggwbqi2is49ajc-glib-2.44.0/lib/libglib-2.0.so.0 [g_main_context_dispatch]
/gnu/store/j02321iwdqyrpdrd53ggwbqi2is49ajc-glib-2.44.0/lib/libglib-2.0.so.0 [???]
/gnu/store/j02321iwdqyrpdrd53ggwbqi2is49ajc-glib-2.44.0/lib/libglib-2.0.so.0 [g_main_context_iteration]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QEventDispatcherGlib::processEvents]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QEventLoop::exec]
/gnu/store/2hvlhvrf7svbc8q77z855030c2h0kbgh-qt-5.4.1/lib/libQt5Core.so.5 [QCoreApplication::exec]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [main]
/gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6 [__libc_start_main]
/gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor [_start]
~~~~~~~~~~~~~~~~~

On the command line I don't see much more than the failure to access
/dev/snd/seq:

~~~~~~~~~~~~~~~~~
rekado@banana guix $ /gnu/store/890wi8llri9x6kmghy8jcnsv3w703yf5-powertabeditor-2.0.0-alpha7/bin/powertabeditor 
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiOutAlsa::initialize: error creating ALSA sequencer client object.

Segmentation fault
rekado@banana guix $ 
~~~~~~~~~~~~~~~~~

When I modprobe the kernel modules `snd-seq*` I no longer see the error,
as this creates /dev/snd/seq.

~~ Ricardo

**Comment by cameronwhite** [comment]
Thanks! You can pass `-DCMAKE_BUILD_TYPE=Debug` when running CMake to get a debug build.

**Comment by rekado** [comment]
With a debug build there's no segfault but an assertion failure:

~~~
rekado@banana ~ $ /gnu/store/9gvhkvb1bcmxkg9mp6mffb0rdlsr292d-powertabeditor-2.0.0-alpha7/bin/powertabeditor 
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiOutAlsa::initialize: error creating ALSA sequencer client object.

powertabeditor: /tmp/nix-build-powertabeditor-2.0.0-alpha7.drv-1/powertabeditor-2.0.0-alpha7/source/audio/midioutputdevice.cpp:53: MidiOutputDevice::MidiOutputDevice(): Assertion `!myMidiOuts.empty() && "No MIDI APIs compiled"' failed.
Aborted (core dumped)
~~~

Looking at the core I don't get much more information:

~~~
(gdb) bt
#0  0x00007f73400f9297 in raise () from /gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6
#1  0x00007f73400fa69a in abort () from /gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6
#2  0x00007f73400f2396 in __assert_fail_base ()
   from /gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6
#3  0x00007f73400f2442 in __assert_fail ()
   from /gnu/store/hy2hi0zj5hrqkmkhpdxf04c9bcnlnsf9-glibc-2.21/lib/libc.so.6
#4  0x0000000000985370 in MidiOutputDevice::MidiOutputDevice() ()
#5  0x0000000000958264 in PreferencesDialog::PreferencesDialog(QWidget*, std::shared_ptr<SettingsPubSub>, TuningDictionary const&) ()
#6  0x00000000008a281e in PowerTabEditor::editPreferences() ()
#7  0x0000000000909765 in PowerTabEditor::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
~~~

Running the regular build in `gdb` I only see a segfault in `MidiOutputDevice()`:

~~~
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiOutAlsa::initialize: error creating ALSA sequencer client object.

[New Thread 0x7fffe3fff700 (LWP 28498)]
[New Thread 0x7fffeb009700 (LWP 28497)]

Program received signal SIGSEGV, Segmentation fault.
0x000000000057e78f in MidiOutputDevice::MidiOutputDevice() ()
(gdb) bt
#0  0x000000000057e78f in MidiOutputDevice::MidiOutputDevice() ()
#1  0x00000000005609a4 in PreferencesDialog::PreferencesDialog(QWidget*, std::shared_ptr<SettingsPubSub>, TuningDictionary const&) ()
#2  0x000000000050e6e8 in PowerTabEditor::editPreferences() ()
#3  0x0000000000529caa in PowerTabEditor::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
~~~
